id: 134713a63503438b92dc1cb692390265
title: Toh_178-Teaching_on_the_Aids_to_Enlightenment-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-060-007
  eft-text-version: 1.1.1 2019
